const actionTypes = {
    ADD_COLOR_TO_LIST: 'ADD_COLOR_TO_LIST',
    REMOVE_COLOR_FROM_LIST: 'REMOVE_COLOR_FROM_LIST',
    UPDATE_FAVOURITE_LIGHT_COLOR: 'UPDATE_FAVOURITE_LIGHT_COLOR',
    UPDATE_FAVOURITE_DARK_COLOR: 'UPDATE_FAVOURITE_DARK_COLOR',
    UPDATE_RANDOM_COLOR: 'UPDATE_RANDOM_COLOR',
};

export default actionTypes;